theme: jekyll-theme-minimal
title: Felipe Espinoza
description: Senior Data Analyst
logo: https://raw.githubusercontent.com/f-espinoza/Felipe_Espinoza/main/images/user_img_2.jpg
show_downloads: false
